package ua.maker.gbible.constant;

public class BooksId {
	
	public static final int BITIE_ID = 1;
	public static final int ISHOD_ID = 2;
	public static final int LEVIT_ID = 3;
	public static final int NUMBER_ID = 4;
	public static final int VTOROZ_ID = 5;
	public static final int IISUS_NAVIN_ID = 6;
	public static final int SUDII_ID = 7;
	public static final int RUTH_ID = 8;
	public static final int ONE_CARSTV_ID = 9;
	public static final int TWO_CARSTV_ID = 10;
	public static final int THREE_CARSTV_ID = 11;
	public static final int FOUR_CARSTV_ID = 12;
	public static final int ONE_PARALIPAM_ID = 13;
	public static final int TWO_PARALIPAM_ID = 14;
	public static final int EZDRA_ID = 15;
	public static final int NEEMIA_ID = 16;
	public static final int ESFIR_ID = 17;
	public static final int IOV_ID = 18;
	public static final int PSALTIR_ID = 19;
	public static final int PRITCHI_ID = 20;
	public static final int ECCL_ID = 21;
	public static final int PESNI_PESNEY_ID = 22;
	public static final int ISAIA_ID = 23;
	public static final int IEREMIA_ID = 24;
	public static final int PLACH_IEREM_ID = 25;
	public static final int IZEKIIL_ID = 26;
	public static final int DANIIL_ID = 27;
	public static final int OSIA_ID = 28;
	public static final int IOIL_ID = 29;
	public static final int AMOS_ID = 30;
	public static final int AVDIY_ID = 31;
	public static final int IONA_ID = 32;
	public static final int MICHEY_ID = 33;
	public static final int NAUM_ID = 34;
	public static final int AVVAKUM_ID = 35;
	public static final int SOFONIA_ID = 36;
	public static final int AGGEY_ID = 37;
	public static final int ZAHARIA_ID = 38;
	public static final int MALAKHIA_ID = 39;
	
	public static final int MATFEY_ID = 40;
	public static final int MARK_ID = 41;
	public static final int LUKA_ID = 42;
	public static final int IOANNA_ID = 43;
	public static final int DEYANIA_ID = 44;
	public static final int IAKOVA_ID = 45;
	public static final int ONE_PETRA_ID = 46;
	public static final int TWO_PETRA_ID = 47;
	public static final int ONE_IOANNA_ID = 48;
	public static final int TWO_IOANNA_ID = 49;
	public static final int THREE_IOANNA_ID = 50;
	public static final int IUDY_ID = 51;
	public static final int RIMLAN_ID = 52;
	public static final int ONE_KORINHANAM_ID = 53;
	public static final int TWO_KORINHANAM_ID = 54;
	public static final int GALATAM_ID = 55;
	public static final int EFESANAM_ID = 56;
	public static final int FILIPIYCAM_ID = 57;
	public static final int KOLOSYANAM_ID = 58;
	public static final int ONE_FESOLONIKIYCAM_ID = 59;
	public static final int TWO_FESOLONIKIYCAM_ID = 60;
	public static final int ONE_TIMOFEY_ID = 61;
	public static final int TWO_TIMOFEY_ID = 62;
	public static final int TITU_ID = 63;
	public static final int FILIMONU_ID = 64;
	public static final int EVREYAM_ID = 65;
	public static final int OTKROVENIE_ID = 66;

}
